services:
  - type: web
    name: demohotel19may25
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build:production
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    nodeVersion: 18.20.8 