services:
  - type: web
    name: demohotel19may25
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:production
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    nodeVersion: 18.20.8 