version: "3.9"
services:
  app:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    container_name: demo-hotel-app
    ports:
      - "10000:10000"
    environment:
      NODE_ENV: production
      PORT: 10000
      MEMORY_LIMIT_PERCENT: 80
      MEMORY_CRITICAL_PERCENT: 90
      MEMORY_CHECK_INTERVAL_MS: 30000
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:10000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
